version: '3.8'
services:
  api-gateway:
    build:
      context: .
      dockerfile: ./apps/api-gateway/Dockerfile
      target: development
    command: npm run start:dev api-gateway
    container_name: api-gateway
    networks:
      - app-network
    ports:
      - '3001:3001'
    env_file:
      - ./apps/api-gateway/.env.production
    depends_on:
      - rabbitmq
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: npm run start:dev auth
    container_name: auth
    networks:
      - app-network
    env_file:
      - ./apps/auth/.env.production
    depends_on:
      - mongodb-auth
      - rabbitmq
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  products:
    build:
      context: .
      dockerfile: ./apps/products/Dockerfile
      target: development
    command: npm run start:dev products
    container_name: products
    networks:
      - app-network
    env_file:
      - ./apps/products/.env.production
    depends_on:
      - mongodb-products
      - rabbitmq
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    networks:
      - app-network
    ports:
      - '5672:5672'
      - '15672:15672'     # For RabbitMQ Management Console

  mongodb-auth:
    image: mongo
    container_name: mongodb-auth
    networks:
      - app-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password123
    volumes:
      - mongodb_auth_data:/data/db
    ports:
      - '27019:27017'

  mongodb-products:
    image: mongo
    container_name: mongodb-prod
    networks:
      - app-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password123
    volumes:
      - mongodb_products_data:/data/db
    ports:
      - '27018:27017'

volumes:
  mongodb_auth_data:
    driver: local
  mongodb_products_data:
    driver: local

networks:
  app-network:
    driver: bridge
