export enum EVENTS {
  NewUser = 'NewUser',
}

export enum APP {
  API_GATEWAY_SERVICE = 'API_GATEWAY_SERVICE',
  AUTH_SERVICE = 'AUTH_SERVICE',
  PRODUCTS_SERVICE = 'PRODUCTS_SERVICE',
}

export enum REQUESTS {
  GET_PRODUCTS = 'GET_PRODUCTS',
  POST_PRODUCTS = 'POST_PRODUCTS',
  PUT_PRODUCT_BY_ID = 'PUT_PRODUCT_BY_ID',
}
