export enum EVENTS {
  NewUser = 'NewUser',
}

export enum APP {
  API_GATEWAY_SERVICE = 'API_GATEWAY_SERVICE',
  AUTH_SERVICE = 'AUTH_SERVICE',
  PRODUCTS_SERVICE = 'PRODUCTS_SERVICE',
}

export enum REQUESTS {
  GET_PRODUCTS = 'GET_PRODUCTS',
  GET_PRODUCT_BY_ID = 'GET_PRODUCT_BY_ID',
  POST_PRODUCTS = 'POST_PRODUCTS',
  PUT_PRODUCT_BY_ID = 'PUT_PRODUCT_BY_ID',
}


export enum AUTH_REQUESTS {
  GET_USERS = 'GET_USERS',
  GET_USER_BY_ID = 'GET_USER_BY_ID',
  POST_USERS = 'POST_USERS',
  PUT_USER_BY_ID = 'PUT_USER_BY_ID',
}